# Generated by Django 3.0.8 on 2020-07-15 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCrypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8)),
                ('current_price', models.CharField(max_length=15)),
                ('previous_price', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('spent', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cryptos', to=settings.AUTH_USER_MODEL)),
                ('reference_crypto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='manager.ReferenceCrypto')),
            ],
        ),
    ]
