# Generated by Django 3.0.8 on 2020-07-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='u_id',
            field=models.UUIDField(default='fbd204a7-318e-4dd3-86e0-e6d524fc3f98'),
            preserve_default=False,
        ),
    ]
