# Generated by Django 3.0.8 on 2020-07-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_crypto_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencecrypto',
            old_name='previous_price',
            new_name='previous_prices',
        ),
    ]
