# Generated by Django 3.0.8 on 2020-07-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200717_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencecrypto',
            name='current_time',
            field=models.CharField(default='shits', max_length=15),
            preserve_default=False,
        ),
    ]
