# Generated by Django 3.0.8 on 2020-07-17 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20200717_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecrypto',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 17, 3, 47, 4, 27251), max_length=30),
        ),
    ]
