# Generated by Django 3.0.8 on 2020-07-17 03:51

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20200717_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 17, 3, 51, 35, 821419), max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='previous_balances_times',
            field=django_mysql.models.ListTextField(models.CharField(max_length=30), default='123ad', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referencecrypto',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 17, 3, 51, 35, 822920), max_length=30),
        ),
    ]
