# Generated by Django 3.0.8 on 2020-07-17 18:00

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20200717_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 17, 18, 0, 0, 5069), max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='previous_balances',
            field=django_mysql.models.ListTextField(models.CharField(default='0', max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='previous_balances_times',
            field=django_mysql.models.ListTextField(models.CharField(default=datetime.datetime(2020, 7, 17, 18, 0, 0, 5244), max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='referencecrypto',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 17, 18, 0, 0, 6560), max_length=30),
        ),
    ]
