# Generated by Django 3.0.8 on 2020-07-17 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20200717_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 17, 18, 10, 9, 614867), max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='previous_balances_times',
            field=django_mysql.models.ListTextField(models.CharField(default=datetime.datetime(2020, 7, 17, 18, 10, 9, 615030), max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='reference_crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.ReferenceCrypto'),
        ),
        migrations.AlterField(
            model_name='referencecrypto',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 17, 18, 10, 9, 616309), max_length=30),
        ),
    ]
