# Generated by Django 3.0.8 on 2020-07-27 03:40

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20200720_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 27, 3, 40, 32, 803296), max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='previous_balances_times',
            field=django_mysql.models.ListTextField(models.CharField(default=datetime.datetime(2020, 7, 27, 3, 40, 32, 803466), max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='referencecrypto',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 27, 3, 40, 32, 804842), max_length=30),
        ),
        migrations.AlterField(
            model_name='referencecrypto',
            name='previous_prices_times',
            field=django_mysql.models.ListTextField(models.CharField(default=datetime.datetime(2020, 7, 27, 3, 40, 32, 805009), max_length=30), size=None),
        ),
    ]
