# Generated by Django 3.0.8 on 2020-07-27 04:00

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20200727_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 27, 4, 0, 36, 688437), max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='previous_balances_times',
            field=django_mysql.models.ListTextField(models.CharField(default=datetime.datetime(2020, 7, 27, 4, 0, 36, 688619), max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='referencecrypto',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 27, 4, 0, 36, 690000), max_length=30),
        ),
        migrations.AlterField(
            model_name='referencecrypto',
            name='previous_prices_times',
            field=django_mysql.models.ListTextField(models.CharField(default=datetime.datetime(2020, 7, 27, 4, 0, 36, 690167), max_length=30), size=None),
        ),
    ]
