# Generated by Django 3.0.8 on 2020-07-27 04:01

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20200727_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 27, 4, 1, 25, 899456), max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='previous_balances_times',
            field=django_mysql.models.ListTextField(models.CharField(default=datetime.datetime(2020, 7, 27, 4, 1, 25, 899626), max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='referencecrypto',
            name='current_time',
            field=models.CharField(default=datetime.datetime(2020, 7, 27, 4, 1, 25, 900988), max_length=30),
        ),
        migrations.AlterField(
            model_name='referencecrypto',
            name='previous_prices_times',
            field=django_mysql.models.ListTextField(models.CharField(default=datetime.datetime(2020, 7, 27, 4, 1, 25, 901156), max_length=30), size=None),
        ),
    ]
